name: 'Run Database Migrations'
description: 'Run Alembic database migrations'

inputs:
  host:
    description: 'Target server host/IP'
    required: true
  username:
    description: 'SSH username'
    required: true
  ssh-key:
    description: 'SSH private key'
    required: true
  app-directory:
    description: 'Application directory name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Execute Database Migrations
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.ssh-key }}
        script: |
          set -e
          echo "🗄️ Running database migrations..."
          
          cd $HOME/${{ inputs.app-directory }}
          source venv/bin/activate
          
          ALEMBIC_CWD="$PWD/venv/bin/alembic"
          
          # Check for multiple Alembic heads and merge them if necessary
          echo "Checking Alembic migrations..."
          alembic_heads=$($ALEMBIC_CWD heads | grep -v '^$' | wc -l)
          if [ "$alembic_heads" -gt 1 ]; then
              echo "Multiple Alembic heads detected. Merging heads..."
              $ALEMBIC_CWD merge heads -m "merge heads for deployment" || { 
                echo "Failed to merge Alembic heads"; 
                exit 1; 
              }
              echo "✓ Alembic heads merged"
          fi
          
          $ALEMBIC_CWD upgrade head || { 
            echo "Failed to run Alembic migrations"; 
            exit 1; 
          }
          echo "✓ Database migrations completed"