name: Production Deployment Workflow

on:
  push:
    branches:
      - main



jobs:
  dev-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Deploy to Production Server
        uses: ./.github/actions/deploy-to-server
        with:
          host: ${{ secrets.LINUX_ONE_VM_IP }}
          username: ${{ secrets.LINUX_ONE_VM_USERNAME }}
          ssh-key: ${{ secrets.LINUX_ONE_VM_SSH_KEY }}
          env-file: ${{ secrets.ENV_FILE }}
          branch: 'main'
          app-directory: 'Bank-Statment-Anaylser-main'